  :oauth:
    :client_id: "22D8KL"
    :client_secret: "287190bc25b82313d6da97950a01bba0"
    :token: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMkQ4M00iLCJzdWIiOiI2V005NzUiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyc29jIHJzZXQgcmFjdCBybG9jIHJ3ZWkgcmhyIHJwcm8gcm51dCByc2xlIiwiZXhwIjoxNTQxNTQyNjE4LCJpYXQiOjE1NDEwMTg0MzR9.O5o5UyTWXbxGED5B7JSbfnsvtOHsrYQdIPF7xOnnWq0"
    