  :oauth:
    :client_id: "22D8KL"
    :client_secret: "287190bc25b82313d6da97950a01bba0"
    :token: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMkQ4S0wiLCJzdWIiOiI2V005NzUiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJyc29jIHJhY3QgcnNldCBybG9jIHJ3ZWkgcmhyIHJudXQgcnBybyByc2xlIiwiZXhwIjoxNTQyMTU0MDg5LCJpYXQiOjE1NDE2MTU3Njh9.TS-CLuh4dfvtK7iZZHbMO2lCR-ep8McZ3InL8_jHuIQ"