#Using Authentication Mode (Need to Revisit)
#FITBIT_URL: 'https://www.fitbit.com/oauth2/authorize?response_type=code&client_id=22D83M&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fpages%2Fdashboard&scope=activity%20heartrate%20location%20nutrition%20profile%20settings%20sleep%20social%20weight&expires_in=604800'

#Using Implicit Authentication Mode (Use for DEV/TEST)
#FITBIT_URL: 'https://www.fitbit.com/oauth2/authorize?response_type=token&client_id=22D83M&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fpages%2Fdashboard&scope=activity%20heartrate%20location%20nutrition%20profile%20settings%20sleep%20social%20weight&expires_in=604800'

#HEROKU URL
FITBIT_URL: 'https://www.fitbit.com/oauth2/authorize?response_type=token&client_id=22D83M&redirect_uri=https%3A%2F%2Ffit-wear.herokuapp.com%2Fpages%2Fdashboard&scope=activity%20heartrate%20location%20nutrition%20profile%20settings%20sleep%20social%20weight&expires_in=604800'